### ISSUE TITLE
Can't add app registration to Global Reader

### ISSUE THREAD

**Issue by wi5nia** [Cj-Scott/Get-AppRegistrationExpiration#3]
My AAD does not allow to add my app registration to the global reader role. Any pointers on how to do this?
I was only able to do it by creating an AAD group, adding the app registration to it and assigning the AAD role to that group.

**Comment by Cj-Scott** [comment]
You could use specific Graph API permissions as well. I haven't tested it but but a colleague suggested adding the "Directory.Read.All" permission.
