### ISSUE TITLE
KCL query App Registration Expiration gives and error

### ISSUE THREAD

**Issue by guidovbrakel** [Cj-Scott/Get-AppRegistrationExpiration#4]
This query gives me an error
```
AppRegistrationExpiration_CL | where DaysToExpiration_d <= 30 //Change this value to the expiration threshold 
| project TimeGenerated, DisplayName_s, ApplicationId_Guid_g, Type_s, StartDate_value_t, EndDate_value_t, Status_s, DaysToExpiration_d
```

The request had some invalid properties
'where' operator: Failed to resolve table or column expression named 'AppRegistrationExpiration_CL'

**Comment by Cj-Scott** [comment]
Did you rename your table to something else? Looks like AppRegistrationExpiration_CL doesnt exist.

**Comment by guidovbrakel** [comment]
> Did you rename your table to something else? Looks like AppRegistrationExpiration_CL doesnt exist.

Nope, but it's fixed. The Automation Runbook wasn't running due to a missing Az.Resources module.

**Comment by Cj-Scott** [comment]
Thatd do it, Glad you got it running.

**Comment by KonstantinKloster** [comment]
@Cj-Scott hey Scott,
i solved the Steps till the KustoQuery,
i just did all your Steps, without doing any changes or other stuff.
My Error ist the Same 

"
BadArgumentError- 'summarize' operator: Failed to resolve table or column expression named 'AppRegistrationExpiration_CL'
"

And i took the KustoQuery u shared with us: "AppRegistrationExpiration_CL | summarize arg_max(TimeGenerated,*) by ApplicationId_Guid_g | where DaysToExpiration_d <= 50 //Change this value to the expiration threshold 
| where TimeGenerated > ago(1d) | project TimeGenerated, DisplayName_s, ApplicationId_Guid_g, Type_s, StartDate_value_t, EndDate_value_t, Status_s, DaysToExpiration_d"

**Comment by CJScott88** [comment]
@KonstantinKloster Please check the log analytics workspace and make sure the custom log is available. If so then please examine the schema and make sure a property name has not changed. I have been seeing different Azure environments on a newer version of the schema where table column names (Properties) have been changed.

**Comment by balagcpcloud** [comment]
Hello Team , 

Am failing with error while running the below kusto query , please suggest any solution to resolve the issue 
BadArgumentError- 'summarize' operator: Failed to resolve table or column expression named 'AppRegistrationExpiration_CL'
 This query doesn't return an Azure resource ID column, so the alert will fire on the entire rule scope [Learn more](https://docs.microsoft.com/azure/azure-monitor/platform/alerts-unified-log?WT.mc_id=Portal-Microsoft_Azure_Monitoring#split-by-alert-dimensions)
